server:
  port: 8081

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: client-microservice
          uri: lb://client-microservice
          predicates:
            - Path=/client-microservice/**
          filters:
            - StripPrefix=1
        - id: import-export-service
          uri: lb://import-export-service
          predicates:
            - Path=/import-export-service/**
          filters:
            - StripPrefix=1
        - id: Product-microservice
          uri: lb://Product-microservice
          predicates:
            - Path=/Product-microservice/**
          filters:
            - StripPrefix=1
        - id: Notification-Rabbitmq-service
          uri: lb://Notification-Rabbitmq-service
          predicates:
            - Path=/Notification-Rabbitmq-service/**
          filters:
            - StripPrefix=1
            - name: RewritePath
              args:
                regexp: '/Notification-Rabbitmq-service(?<remaining>.*)'
                replacement: '${remaining}'
        - id: User-Auth-service
          uri: lb://User-Auth-service
          predicates:
            - Path=/User-Auth-service/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
